### ISSUE TITLE
Build errors with Node 10.x on Debian 9

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/rdf-canonize#4]
Node 10.x is now available via `nvm` and [nodesource](https://github.com/nodesource/distributions#installation-instructions)

rdf-canonize fails to build, here is the error:
```
> rdf-canonize@0.2.3 install /home/matt/dev/bedrock-dev/bedrock-passport/test/node_modules/rdf-canonize
> node-gyp rebuild

make: Entering directory '/home/matt/dev/bedrock-dev/bedrock-passport/test/node_modules/rdf-canonize/build'
  CXX(target) Release/obj.target/urdna2015/lib/native/IdentifierIssuer.o
  CXX(target) Release/obj.target/urdna2015/lib/native/MessageDigest.o
In file included from ../lib/native/MessageDigest.cc:10:0:
../lib/native/MessageDigest.h:14:14: error: field ‘context’ has incomplete type ‘EVP_MD_CTX {aka evp_md_ctx_st}’
   EVP_MD_CTX context;
              ^~~~~~~
In file included from /home/matt/.node-gyp/10.0.0/include/node/openssl/evp.h:14:0,
                 from ../lib/native/MessageDigest.h:9,
                 from ../lib/native/MessageDigest.cc:10:
/home/matt/.node-gyp/10.0.0/include/node/openssl/ossl_typ.h:92:16: note: forward declaration of ‘EVP_MD_CTX {aka struct evp_md_ctx_st}’
 typedef struct evp_md_ctx_st EVP_MD_CTX;
                ^~~~~~~~~~~~~
../lib/native/MessageDigest.cc: In destructor ‘RdfCanonize::MessageDigest::~MessageDigest()’:
../lib/native/MessageDigest.cc:35:30: error: ‘EVP_MD_CTX_cleanup’ was not declared in this scope
   EVP_MD_CTX_cleanup(&context);
                              ^
urdna2015.target.mk:105: recipe for target 'Release/obj.target/urdna2015/lib/native/MessageDigest.o' failed
make: *** [Release/obj.target/urdna2015/lib/native/MessageDigest.o] Error 1
make: Leaving directory '/home/matt/dev/bedrock-dev/bedrock-passport/test/node_modules/rdf-canonize/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/matt/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.9.0-6-amd64
gyp ERR! command "/home/matt/.nvm/versions/node/v10.0.0/bin/node" "/home/matt/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/matt/dev/bedrock-dev/bedrock-passport/test/node_modules/rdf-canonize
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

**Comment by davidlehn** [comment]
Fixed and 0.2.4 released.
